SCHEME := "Kowalski"

MACOS_DESTINATION := "platform=macOS"

# List available commands
default:
    just --list --unsorted

# Run all tests for the Kowalski scheme on macOS
test:
    set -o pipefail && xcodebuild test -scheme {{ SCHEME }} \
        -destination {{ MACOS_DESTINATION }} | xcpretty
